cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/dmg_sound/rom_singles/01-registers.gb"
cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/cgb_sound/rom_singles/01-registers.gb"
cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/dmg_sound/rom_singles/02-len ctr.gb"
cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/cgb_sound/rom_singles/02-len ctr.gb"
cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/dmg_sound/rom_singles/03-trigger.gb"
cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/cgb_sound/rom_singles/03-trigger.gb"
cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/dmg_sound/rom_singles/06-overflow on trigger.gb"
cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/cgb_sound/rom_singles/06-overflow on trigger.gb"
cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/dmg_sound/rom_singles/08-len ctr during power.gb"
cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/cgb_sound/rom_singles/08-len ctr during power.gb"
cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/dmg_sound/rom_singles/10-wave trigger while on.gb"
cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/cgb_sound/rom_singles/10-wave trigger while on.gb"
cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/dmg_sound/rom_singles/11-regs after power.gb"
cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/cgb_sound/rom_singles/11-regs after power.gb"


# cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/dmg_sound/rom_singles/04-sweep.gb"
# cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/cgb_sound/rom_singles/04-sweep.gb"
# cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/dmg_sound/rom_singles/05-sweep details.gb"
# cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/cgb_sound/rom_singles/05-sweep details.gb"
# cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/dmg_sound/rom_singles/07-len sweep period sync.gb"
# cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/cgb_sound/rom_singles/07-len sweep period sync.gb"
# cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/dmg_sound/rom_singles/09-wave read while on.gb"
# cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/cgb_sound/rom_singles/09-wave read while on.gb"
# cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/dmg_sound/rom_singles/12-wave.gb"
# cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/cgb_sound/rom_singles/12-wave.gb"

# cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/dmg_sound/dmg_sound.gb"
# cargo run --release -- --mode blargg-memory-output -s 8 "res/gb-test-roms/cgb_sound/cgb_sound.gb"
